name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker-ecommerce-frontend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./docker-ecommerce-backend
        file: ./docker-ecommerce-backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest

    # Add deployment steps here (e.g., SSH into server and run docker-compose up -d)
    # - name: Deploy to production
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     ssh user@your-server "cd /path/to/app && docker-compose pull && docker-compose up -d"
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
