name: Docker CI/CD - Ecommerce App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug - List directory contents
      run: |
        ls -la
        echo "Frontend directory contents:"
        ls -la docker-ecommerce-frontend/ || echo "Frontend directory not found"
        echo "Backend directory contents:"
        ls -la docker-ecommerce-backend/ || echo "Backend directory not found"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./docker-ecommerce-frontend
        file: ./docker-ecommerce-frontend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./docker-ecommerce-backend
        file: ./docker-ecommerce-backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest