name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Debug - List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "\nRoot directory contents:"
        ls -la
        echo "\nFrontend directory contents:"
        ls -la docker-ecommerce-frontend/ || echo "Frontend directory not found"
        echo "\nBackend directory contents:"
        ls -la docker-ecommerce-backend/ || echo "Backend directory not found"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker-ecommerce-frontend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker-ecommerce-backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest
